//! # Verdant procedural art
//!
//! Deterministic, palette-enforced pixel-art generation.
//!
//! ## Why generate rather than fetch
//!
//! The blueprint this engine follows proposes a generative asset pipeline
//! driven by cloud diffusion services. That pipeline has three properties that
//! make it unsuitable as a game's *only* source of art: it is non-deterministic
//! (the same prompt and seed can drift between model versions), it costs money
//! per image, and its licensing rests on a provider's terms of service rather
//! than on anything the project owns.
//!
//! This module takes the other route. Art is generated by explicit algorithms
//! from a seed, which means:
//!
//! * **Reproducible.** The same seed produces the same bytes, on every machine,
//!   forever. A sprite can be content-addressed and a visual bug reproduced
//!   from its [`Provenance`] record alone.
//! * **Free and offline.** A whole atlas regenerates at startup in
//!   milliseconds; nothing is fetched and nothing is cached.
//! * **Unambiguously licensed.** The output is a function of code in this
//!   repository, with no third-party training data anywhere in its lineage.
//!
//! The trade-off is honest: an algorithm will not out-draw a human artist or a
//! large diffusion model on subject matter it was not written for. What it does
//! give is a coherent, complete, consistent set of art for the shapes it *does*
//! know — characters, terrain, crops, trees, items — which is exactly the set a
//! farming game needs.
//!
//! ## The palette constraint
//!
//! Restricting output to a small palette is what separates generated pixel art
//! from noise, and it is the property general image models struggle to hold.
//! Here it is structural rather than a post-process: a [`Canvas`] stores
//! *palette indices*, so an off-palette colour is not expressible.
//!
//! ## Example
//!
//! ```
//! use verdant_procgen_art::{generate_character, CharacterStyle, Facing, WALK_FRAMES};
//!
//! let villager = generate_character(20_260_808, 16, 24, CharacterStyle::villager());
//!
//! // Four directions, four walk frames each.
//! assert_eq!(villager.frame_count(), 4 * WALK_FRAMES);
//!
//! // Frames resolve to RGBA bytes ready for the renderer's texture array.
//! let facing_south = Facing::South.index() * WALK_FRAMES;
//! let pixels = villager.frame_rgba(facing_south).expect("frame exists");
//! assert_eq!(pixels.len(), 16 * 24 * 4);
//! ```

#![doc(html_no_source)]

pub mod canvas;
pub mod font;
pub mod generators;
pub mod provenance;

pub use canvas::{Canvas, Palette, PaletteIndex, Rgba};
pub use generators::{
    generate_character, generate_crop, generate_item_icon, generate_terrain_tile, generate_tree,
    CharacterStyle, Facing, GeneratedSprite, WALK_FRAMES,
};
pub use provenance::{AssetKind, Provenance};
